docker pull rodrigomelgar/kepimetheus:0.0.1
docker pull grafana/grafana:11.2.1
docker pull quay.io/prometheus-operator/prometheus-config-reloader:v0.77.1
docker pull quay.io/prometheus-operator/prometheus-operator:v0.77.1
docker pull quay.io/prometheus/prometheus:v2.54.1
docker pull registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0
docker pull quay.io/prometheus/node-exporter:v1.8.2
docker pull quay.io/kiwigrid/k8s-sidecar:1.27.4
docker pull quay.io/prometheus/alertmanager:v0.27.0
